version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: learning-platform
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # DataDog Agent service
  datadog-agent:
    image: datadog/agent:latest
    container_name: datadog-agent
    restart: always
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=us5.datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
    ports:
      - "8125:8125/udp"  # StatsD port
      - "8126:8126/tcp"  # APM port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    networks:
      - app-network

  # NestJS application service
  app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb:27017/learning-platform
      - DATADOG_HOST=datadog-agent
      - DATADOG_PORT=8125
    depends_on:
      - mongodb
      - datadog-agent
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
